import json,re,time
from pathlib import Path
from genlayer_py import create_account,create_client
from genlayer_py.chains import studionet

ROOT=Path(__file__).parents[1]; ENV=(ROOT.parents[3]/'accounts.env').read_text(encoding='utf-8'); ADDRESS='0x38FF51c53b0063513297c355c84Be228E30FfB8f'; COMMIT='84e3f3644ca1c46750a8bf76f994bf64dafc8fe1'
def account(slot):
    key=re.search(rf'^ACCOUNT_{slot}_GENLAYER_PRIVATE_KEY\s*=\s*"?([^"\r\n]+)',ENV,re.M).group(1).strip();return create_account(account_private_key=key)
def send(client,name,args):
    tx=client.write_contract(address=ADDRESS,function_name=name,args=args,value=0);print(name+'='+str(tx),flush=True);receipt=client.wait_for_transaction_receipt(transaction_hash=tx,status='FINALIZED',retries=180,interval=5000,full_transaction=True);leader=(receipt.get('consensus_data',{}).get('leader_receipt') or [{}])[0];assert receipt.get('status_name')=='FINALIZED' and str(receipt.get('result_name')).upper()=='MAJORITY_AGREE' and str(leader.get('execution_result')).upper()=='SUCCESS',(name,receipt);return str(tx)
owner,reviewer=account(1),account(2); owner_client=create_client(chain=studionet,account=owner); reviewer_client=create_client(chain=studionet,account=reviewer); release_id='PS-LIVE-'+str(int(time.time()))
urls={'policy':f'https://raw.githubusercontent.com/SAMiiNW/patch-semaphore/{COMMIT}/docs/evidence/policy.txt','manifest':'https://samiinw-patch-semaphore.pages.dev/evidence/manifest-vulnerable.txt','advisory':f'https://cdn.jsdelivr.net/gh/SAMiiNW/patch-semaphore@{COMMIT}/docs/evidence/advisory.txt','patched':'https://samiinw-patch-semaphore.pages.dev/evidence/manifest-patched.txt','report':f'https://github.com/SAMiiNW/patch-semaphore/raw/{COMMIT}/docs/evidence/patch-report.txt'}
transactions={};transactions['register']=send(owner_client,'register_release',[release_id,reviewer.address,'patch-semaphore-demo','4.0.0',urls['policy'],urls['manifest'],urls['advisory'],3600]);transactions['scan']=send(owner_client,'scan_release',[release_id]);quarantined=owner_client.read_contract(address=ADDRESS,function_name='get_release',args=[release_id]);assert quarantined['state']=='QUARANTINED',quarantined;transactions['patch']=send(owner_client,'submit_patch',[release_id,urls['patched'],urls['report']]);awaiting=owner_client.read_contract(address=ADDRESS,function_name='get_release',args=[release_id]);assert awaiting['state']=='AWAITING_REVIEW',awaiting;transactions['approve']=send(reviewer_client,'approve_clearance',[release_id]);final=owner_client.read_contract(address=ADDRESS,function_name='get_release',args=[release_id]);assert final['state']=='CLEARED',final;print(json.dumps({'releaseId':release_id,'state':final['state'],'severity':final['severity'],'component':final['component'],'patchVersion':final['patch_version'],'transactions':transactions},default=str),flush=True)
